name: Build and publish little-queue

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: run build script
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Repo ${DOCKER_REPO}"
          echo "User ${DOCKER_USER}"
          ./dockerhub.sh